var quotes = [
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe you can and you're halfway there.",
    "The best revenge is massive success.",
    "In the middle of every difficulty lies opportunity.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The secret of getting ahead is getting started.",
    "Don't watch the clock; do what it does. Keep going.",
    "If you want to achieve greatness, stop asking for permission.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Don't be afraid to give up the good to go for the great.",
    "The only person you should try to be better than is the person you were yesterday.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you can dream it, you can achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best revenge is massive success.",
    "The successful warrior is the average man, with laser-like focus.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not just about making money. It's about making a difference.",
    "The journey of a thousand miles begins with a single step.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The successful warrior is the average man, with laser-like focus.",
    "There are no shortcuts to any place worth going.",
    "Success is not in what you have, but who you are.",
    "The only thing standing between you and your goal is the story you keep telling yourself why you can't achieve it.",
    "The key to success is to focus on goals, not obstacles.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Don't be afraid to give up the good to go for the great.",
    "The only person you should try to be better than is the person you were yesterday.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best revenge is massive success.",
    "The successful warrior is the average man, with laser-like focus.",
    "Success is not just about making money. It's about making a difference.",
    "The journey of a thousand miles begins with a single step.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The successful warrior is the average man, with laser-like focus.",
    "There are no shortcuts to any place worth going.",
    "Success is not in what you have, but who you are.",
    "The only thing standing between you and your goal is the story you keep telling yourself why you can't achieve it.",
    "The key to success is to focus on goals, not obstacles.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Don't be afraid to give up the good to go for the great.",
    "The only person you should try to be better than is the person you were yesterday.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "You must expect great things of yourself before you can do them.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "The only way to do great work is to love what you do.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best revenge is massive success.",
    "In the middle of every difficulty lies opportunity.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The secret of getting ahead is getting started.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "Believe you can and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The only way to do great work is to love what you do.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Believe you can and you're halfway there.",
    "The best revenge is massive success.",
    "In the middle of every difficulty lies opportunity.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The secret of getting ahead is getting started.",
    "Don't watch the clock; do what it does. Keep going.",
    "If you want to achieve greatness, stop asking for permission.",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination.",
    "The biggest risk is not taking any risk. In a world that's changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Don't be afraid to give up the good to go for the great.",
    "The only person you should try to be better than is the person you were yesterday.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is walking from failure to failure with no loss of enthusiasm.",
    "If you can dream it, you can achieve it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "The best revenge is massive success.",
    "The successful warrior is the average man, with laser-like focus.",
    "I find that the harder I work, the more luck I seem to have.",
    "Success is not just about making money. It's about making a difference.",
    "The journey of a thousand miles begins with a single step.",
    "I attribute my success to this: I never gave or took any excuse.",
    "The successful warrior is the average man, with laser-like focus.",
    "There are no shortcuts to any place worth going.",
    "Success is not in what you have, but who you are.",
    "The only thing standing between you and your goal is the story you keep telling yourself why you can't achieve it.",
    "The key to success is to focus on goals, not obstacles.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "Don't be afraid to give up the good to go for the great.",
    "The only person you should try to be better than is the person you were yesterday.",
    "You are never too old to set another goal or to dream a new dream.",
    "Success is not the absence of failure; it's the persistence through failure.",
    "You must expect great things of yourself before you can do them.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "The only way to do great work is to love what you do.",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best revenge is massive success.",
    "In the middle of every difficulty lies opportunity.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The secret of getting ahead is getting started.",
    "Don't watch the clock; do what it does. Keep going.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It does not matter how slowly you go, as long as you do not stop.",
    "Believe you can and you're halfway there.",
    "Success is not final, failure is not fatal: It is the courage to continue that counts."
  ];
  
  var quote = document.getElementById('enter-innerText')

function quoteGenerator() {

    var randomNumber = Math.floor(Math.random() * 100);

    quote.innerText = quotes[randomNumber]


}
